# https://github.com/elastic/elasticsearch-docker
FROM elasticsearch:5.1.1

#RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install mobz/elasticsearch-head 
#RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install lmenezes/elasticsearch-kopf 


#ADD config/elasticsearch.yml /usr/share/elasticsearch/config
#ADD config/logging.yml /usr/share/elasticsearch/config

#CMD chmod a+rwx  /usr/share/elasticsearch/config/elasticsearch.yml

#ADD config/elasticsearch.yml /etc/elasticsearch/config
#ADD config/elasticsearch.yml /etc/elasticsearch/config

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu

